name: ${project.name}
author: ${project.organization.name}
version: ${project.version}

main: ${bukkitMain}
load: STARTUP

softdepend: ["PowerNBT"]

commands:
    ctm:
        description: "base continuum command"
        usage: "/ctm <subcommand>"
